### PR TITLE
Migrate entire project to NextJS

### PR DESCRIPTION
**Pull request by yuvadm**
This branch prepares `v2` with the following updates:
- [x] Migrate entire project to a more modern NextJS-based setup
- [x] Migrate to Tailwind CSS styling
- [x] Migrate to NPM
- [x] Tighten project design
- [x] Keep functionality as-is
- [ ] Move deployment to Vercel

### CODE REVIEW

**Review by aravindvnair99 — COMMENTED** [review]
Requested Vercel access

**Comment by yuvadm** [comment]
@aravindvnair99 The project is on my personal account so I'd rather not add any collaborators there.

Also there isn't much to configure there once everything is setup. I hope that makes sense.

**Comment by aravindvnair99** [comment]
@yuvadm No problem, I understand. To clarify, I was requesting access to preview since it was saying I need to request access.

**Comment by yuvadm** [comment]
Oh, that's weird - anyway I setup `v2` branch to build and deploy on https://cidrxyz.vercel.app/

This will also be the production endpoint once we merge to `master`, and domain will point there.

**Comment by aravindvnair99** [comment]
Got it, thanks @yuvadm! This link works.

**Comment by yuvadm** [comment]
Happy to merge this as is, I'd like to add some descriptions to the netmask fields, maybe as hover tooltips, but will continue that work after the merge and DNS update.

**Pull request merged**
