### PR TITLE
Use base and broadcast to reflect actual IPs

### LINKED ISSUE #65: Unintuitive results for "first usable IP"
Hi, first off, I love this website, thank you so much for making it. I use it to explain CIDRs to junior engineers or engineers without a networking background and it really helps them "get it".

For example the CIDR `200.88.135.144/4`, your calculator says the first IP is 192.0.0.1 

cidrs

But I think the first IP address should be 192.0.0.0, as that is the lowest IP address that matches the `1,1,0,0` 4-bit prefix. Other CIDR calculators e.g. https://www.ipaddressguide.com/cidr or the Rust [ipnetwork crate](docs.rs/ipnetwork) agree with me.

Screenshot 2023-01-05 at 12 03 11 PM

I see you're using the [NodeJS netmask package](https://www.npmjs.com/package/netmask) for calculating first/last IPs. So I guess the issue is in the library. According to [this great StackOverflow question](https://stackoverflow.com/questions/14915188/ip-address-ending-with-zero/14915309#14915309) it comes down to whether .0 IPs are really "usable" as some hardware reserves them for the "network ID" and doesn't consider them "real" IPs that devices can use. 

The only reason I bother to go into this much detail is that I frequently use your website for teaching purposes, and to help generate unit tests for code which deals with CIDRs. Maybe the UI could be updated to differentiate between the "usable" IPs and the IPs in the CIDR? I certainly found the differences between different IP calculator websites/libraries confusing.

### PR DESCRIPTION
**Pull request by JimBledsoe**
Base and broadcast are already provided in the library. 
Count moved left where it better reflects the maximum size of the CIDR.
Usable IPs are much more clear now.
Adjusted spacing of the styling to accommodate more columns.

Fixes #65

### CODE REVIEW

**Comment by JimBledsoe** [comment]
image

**Comment by yuvadm** [comment]
Thanks for the PR! Looks good overall, my main concern is with crowding that row with lots of details that aren't always interesting to most users who aren't familiar with CIDR notation.

At the very least perhaps the order of the fields should be ascending: Base -> First Usable -> Last Usable -> Broadcast

**Comment by yuvadm** [comment]
@JimBledsoe Got it, I think that makes more sense to me now.

I'm inclined to just merge the change and at the same time prioritize a redesign that makes things clearer (not to mention responsive #4 ).

@aravindvnair99 any thoughts?

**Review by yuvadm — APPROVED** [review]

**Comment by JimBledsoe** [comment]
I just posted comments on #4

**Review by aravindvnair99 — APPROVED** [review]
LGTM

**Pull request merged**
