### PR TITLE
paste feature requested on #48

### PR DESCRIPTION
**Pull request by ranga543**
* paste on octet inputs or cidr input
* handles just octet paste or full cidr ip paster

### CODE REVIEW

**Comment by yuvadm** [comment]
Thanks for working on this issue! As for the solution, instead of rolling your own regex, I suggest using the `netmask` library which is already available as a dependency.

**Review by aravindvnair99 — APPROVED** [review]

**Comment by aravindvnair99** [comment]
@yuvadm can this be merged after resolving merge conflicts? It's been open for a long time.

**Comment by yuvadm** [comment]
@aravindvnair99 as mentioned in my previous comment, I prefer to see validation with `netmask` as opposed to a custom regex

**Comment by aravindvnair99** [comment]
@ranga543 would you be able to update your code with the same and also resolve the conflict?

**Comment by aravindvnair99** [comment]
@yuvadm need you to update the build image so that changes can be tested properly. I've opened #66 to track this.

**Comment by ranga543** [comment]
@yuvadm Updated code to use netmask instead of regex

**Comment by aravindvnair99** [comment]
Thanks @ranga543! @yuvadm could you review this?

**Comment by aravindvnair99** [comment]
@yuvadm were you able to check this? Could you also trigger a rerun of the deployment?

**Comment by yuvadm** [comment]
@aravindvnair99 yes, the netlify build settings have been updated and current build can be seen on https://deploy-preview-52--cidr.netlify.app/

Any future commits to this branch will probably update the PR properly.

Overall looks good!

**Review by yuvadm — APPROVED** [review]

**Comment by KevinGimbel** [comment]
Awesome thank you! 🙌

**Pull request merged**
