### PR TITLE
change display elements to flexbox

### PR DESCRIPTION
**Pull request by jibin2706**
#4

### CODE REVIEW

**Comment by jibin2706** [comment]
any other changes to make?

**Comment by yuvadm** [comment]
Just switching to flexbox isn't enough. We need to keep the full-width version as is, and just find a nice way to support small width screens on mobile devices. It still doesn't look that good. But I'm willing to make the incremental improvement.

Can you please make sure all the text is aligned to the same width, and that the bottom 4 boxes also don't expand more than that width?

**Comment by jibin2706** [comment]
@yuvadm Should I revert the width to previous width?

**Comment by yuvadm** [comment]
No this width is fine, just make sure all the elements are aligned to the same width.

**Comment by jibin2706** [comment]
adjusted the width @yuvadm

**Comment by jibin2706** [comment]
@yuvadm anything else to add?

**Pull request closed without merging**
